package styles

const (
	// Layout Properties
	Display         = "display"
	Position        = "position"
	Top             = "top"
	Right           = "right"
	Bottom          = "bottom"
	Left            = "left"
	Overflow        = "overflow"
	OverflowX       = "overflow-x"
	OverflowY       = "overflow-y"
	ZIndex          = "z-index"
	Flex            = "flex"
	FlexDirection   = "flex-direction"
	JustifyContent  = "justify-content"
	AlignItems      = "align-items"
	AlignContent    = "align-content"
	FlexWrap        = "flex-wrap"
	Grid            = "grid"
	GridArea        = "grid-area"
	GridColumn      = "grid-column"
	GridColumnEnd   = "grid-column-end"
	GridColumnStart = "grid-column-start"
	GridRow         = "grid-row"
	GridRowEnd      = "grid-row-end"
	GridRowStart    = "grid-row-start"
	GridTemplate    = "grid-template"

	// Box Model Properties
	Width         = "width"
	MaxWidth      = "max-width"
	Height        = "height"
	MaxHeight     = "max-height"
	Padding       = "padding"
	PaddingTop    = "padding-top"
	PaddingRight  = "padding-right"
	PaddingBottom = "padding-bottom"
	PaddingLeft   = "padding-left"
	Margin        = "margin"
	MarginTop     = "margin-top"
	MarginRight   = "margin-right"
	MarginBottom  = "margin-bottom"
	MarginLeft    = "margin-left"
	Border        = "border"
	BorderColor   = "border-color"
	BorderStyle   = "border-style"
	BorderWidth   = "border-width"
	BorderRadius  = "border-radius"
	BoxShadow     = "box-shadow"

	// Fonts & Text Properties
	Color          = "color"
	Font           = "font"
	FontFamily     = "font-family"
	FontSize       = "font-size"
	FontWeight     = "font-weight"
	LineHeight     = "line-height"
	TextAlign      = "text-align"
	TextDecoration = "text-decoration"
	TextTransform  = "text-transform"
	LetterSpacing  = "letter-spacing"
	WhiteSpace     = "white-space"
	TextOverflow   = "text-overflow"

	// Visual Properties
	BackgroundColor  = "background-color"
	Background       = "background"
	BackgroundImage  = "background-image"
	BackgroundRepeat = "background-repeat"
	BackgroundSize   = "background-size"
	Opacity          = "opacity"
	BoxSizing        = "box-sizing"
	Cursor           = "cursor"
	Transition       = "transition"
	Transform        = "transform"

	// List properties
	ListStyle     = "list-style"
	ListStyleType = "list-style-type"

	// Table Properties
	BorderCollapse = "border-collapse"
	BorderSpacing  = "border-spacing"
	TableLayout    = "table-layout"
	CaptionSide    = "caption-side"

	// Other Properties
	Visibility    = "visibility"
	Clip          = "clip"
	Content       = "content"
	Filter        = "filter"
	PointerEvents = "pointer-events"
	Resize        = "resize"
	UserSelect    = "user-select"
)
